apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: removed/info
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: europe-west1
  name: system-test
  namespace: "removed/info"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        client.knative.dev/user-image: removed/info
        run.googleapis.com/client-name: cloud-console
      name: system-test-00003-jeg
    spec:
      containerConcurrency: 1
      containers:
        - image: removed/info
          ports:
            - containerPort: 8080
              name: http1
          resources:
            limits:
              cpu: 4000m
              memory: 8192Mi
      serviceAccountName: removed/info
      timeoutSeconds: 3600
  traffic:
    - latestRevision: true
      percent: 100
